version: "3.9"

services:
  syslog:
    image: balabit/syslog-ng:latest
    container_name: syslog
    hostname: syslog
    restart: unless-stopped
    ports:
      - "514:514/udp"
      - "601:601"
    volumes:
      - /transpara/logs:/var/log
    command: "--no-caps"

  tstore:
    image: docker.io/transpara/portainer_tstore:latest
    shm_size: '2gb'
    volumes:
      - /transpara/tstore_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BorgGoesLive!22
      - PGDATA=/var/lib/postgresql/data
      - PGPORT=5432
    container_name: tstore
    hostname: tstore
    ports:
      - "5435:5432"
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        syslog-format: "rfc3164"
        tag: "node-tstore"

  promscale:
    image: timescale/promscale:latest
    command: '-enable-feature=tracing -otlp-grpc-server-listen-address=:9202'
    ports:
      - "9201:9201"
      - "9202:9202"
    container_name: promscale
    hostname: promscale
    restart: unless-stopped
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://transpara:BorgGoesLive!22@tstore:5432/transpara?sslmode=allow
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        syslog-format: "rfc3164"
        tag: "node-promscale"

  tstore-api:
    image: docker.io/transpara/portainer_tstore-api:latest
    environment:
      - PROMSCALE_DB_URI=postgresql://transpara:BorgGoesLive!22@tstore:5432/transpara
      - PROMSCALE_API_URI=http://promscale:9201/write
      - PROMSCALE_OTLP_URI=http://promscale:9202
      - EXPOSE_METRICS=True
      - EXPORT_TRACES=True
    container_name: tstore-api
    hostname: tstore-api
    ports:
      - "10001:80"
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        syslog-format: "rfc3164"
        tag: "node-tstore-api"

networks:
  default:
    name: transpara
